---
title: "Machine Learning Project"
author: "wpshen"
date: "April 8, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(caret); library(rpart); library(klaR)
set.seed(123456)
data <- read.csv("pml-training.csv", na.strings = c("", "#DIV/0!", "NA"), 
                 row.names=1, stringsAsFactors=FALSE)
data <- data[,colSums(is.na(data))<0.9*nrow(data)] # remove the column is 90% NA
data$classe <- factor(data$classe)
inTrain <- createDataPartition(data$classe, p=0.8, list=FALSE, times=1)
training <- data[inTrain,]
testing <- data[-inTrain,]

accu <- numeric()

# 1. Recursive Partitioning and Regression Trees
fit1 <- train(classe~., method="rpart", data=training)
pred1 <- predict(fit1, testing)
accu[length(accu)+1] <- sum(pred1 == testing$classe)/length(pred1)
confusionMatrix(data = pred1, testing$classe)
importance <- varImp(fit1)

# 2. Random Forest
fit2 <- train(classe~., method="rf", data=training)
pred2 <- predict(fit2, testing)
accu[length(accu)+1] <- sum(pred2 == testing$classe)/length(pred2)
confusionMatrix(data = pred2, testing$classe)
importance <- varImp(fit2)

```


```{r}
valdata <- read.csv("pml-testing.csv", na.strings = c("", "#DIV/0!", "NA"), 
                    row.names=1, stringsAsFactors=FALSE)
valdata <- valdata[,colSums(is.na(valdata))<0.9*nrow(valdata)] # remove the column is 90% NA
valdata$classe <- factor(valdata$classe)

```

